version: "3"
services:
  weather-app:
    image: weather-app:latest
    volumes:
      - ~/logs/weather-app:/logs/weather-app
    environment:
      DB_DSN: root:root@tcp(mysql:3306)/weather?charset=utf8
    ports:
      - 8080:8080
    links:
      - mysql
  zipkin-go:
    image: openzipkin/zipkin
    container_name: zipkin-go
    ports:
      - 9411:9411
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
